### ISSUE TITLE
npm i Step..

### ISSUE THREAD

**Issue by ZuhairAbdulJabbar** [kefranabg/bento-starter#125]
**I got this ..**

zuhair@DESKTOP-K9ATPC4 MINGW64 ~/Desktop/Bento/bento-starter (master)
$ npm i
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

> iltorb@1.3.10 install C:\Users\zuhair\Desktop\Bento\bento-starter\node_modules\iltorb
> detect-libc prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 platform=win32)

C:\Users\zuhair\Desktop\Bento\bento-starter\node_modules\iltorb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\zuhair\Desktop\Bento\bento-starter\node_modules\iltorb
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN eslint-config-airbnb@17.1.0 requires a peer of eslint-plugin-jsx-a11y@^6.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.0 requires a peer of eslint-plugin-react@^7.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iltorb@1.3.10 install: `detect-libc prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@1.3.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zuhair\AppData\Roaming\npm-cache\_logs\2019-04-24T21_41_32_370Z-debug.log

**Comment by kefranabg** [comment]
Hi @ZuhairAbdulJabbar. Can you provide your `npm` and `node` version ?
Did you read the [install prerequisites](https://bento-starter.netlify.com/setup/) ?

**Comment by Foetus6907** [comment]
Hi @kefranabg , i got the same issus. my npm version is 6.4.1 and my node version is v10.15.3.

**Comment by kefranabg** [comment]
Hi @Foetus6907, what is your OS ? Windows ?

**Comment by Foetus6907** [comment]
windows 10

**Comment by kefranabg** [comment]
It seems that one of the `bundlesize` package dependency requires python 2.7. Can you try to run this command : `npm install -g windows-build-tools` and install dependency again and tell if it worked ?

`windows-build-tools` will install tools you need to compile native Node modules : [https://github.com/felixrieseberg/windows-build-tools](https://github.com/felixrieseberg/windows-build-tools)

**Comment by MaeseppTarvo** [comment]
@kefranabg I am sorry to comment a closed issue but I am getting pretty much same errors but with different versions. I am on macOS and these are my npm and node versions:

```
npm --v
6.9.0
node -v
v12.3.1
```

[This](https://gist.github.com/MaeseppTarvo/2a4defc6825967d02be9c8f40cb4c4a1) is the log I get if running `npm run setup` as mentioned in documentation.

I also tried using Yarn but I still run into warnings/errors.

Can you point me to the right direction? Since documentation requirement says node9.3.0+ and npm@5.5.0+ I thought that using newest stable versions would be fine, correct me if I am wrong.
