### ISSUE TITLE
Create a slack ?

### ISSUE THREAD

**Issue by kefranabg** [kefranabg/bento-starter#131]
Would it be interesting to have a bento-starter slack ?

**Comment by tbetous** [comment]
An other possibility would be Gitter. It seems pretty great to talk with a dev community. What do you think about that ?

Slack is also great.

**Comment by kefranabg** [comment]
More people knows slack don't you think ? Discord is also an option

**Comment by tbetous** [comment]
Well, let's try with Slack. We already know well this tool. ;)
