### ISSUE TITLE
Automate removal of git repository

### ISSUE THREAD

**Issue by mbernardeau** [kefranabg/bento-starter#139]
**Is your feature request related to a problem? Please describe.**
In documentation we can read `⚠️ For this step, we assume that you already have a github repository that hosts your bento-starter project with your source code pushed on the master branch ⚠️`.
I think it would be a great addition to this project to automate removal of `.git` folder, creation of a new repository and commiting the initial commit.

**Describe the solution you'd like**
I think the most user-friendly solution would be to create a script which you can run with a npm command. This script should also be able to delete itself before initial commit (as this operation should not be run twice).

**Additional context**
[react-boilerplate](https://github.com/react-boilerplate/react-boilerplate/) uses a script for this specific use-case. Script can be found [here](https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/scripts/setup.js
) and can be run using `npm run setup`.

**Comment by kefranabg** [comment]
I love the idea. Definitely going to add this behavior.

Thanks @mbernardeau 🙏
