### ISSUE TITLE
Improve lodash imports to reduce bundle size

### ISSUE THREAD

**Issue by kefranabg** [kefranabg/bento-starter#142]
- [x] When importing `lodash` functions, use this syntax 
`import isNil from 'lodash/isNil' // => 1KB`
instead of this one
`import { isNil } from 'lodash' // => 70KB`

- [x] And check with `webpack bundle analyser` that the bundle have been reduced.

**Comment by mbernardeau** [comment]
Note that you could also use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) to perform this task at build time

**Comment by kefranabg** [comment]
Thanks for this tip 👍 I'll use that
