### ISSUE TITLE
npm run prettier:check gives error.

### ISSUE THREAD

**Issue by RoyBkker** [kefranabg/bento-starter#155]
**Describe the bug**
npm run prettier:check gives an error in command line.

**To Reproduce**
1. Run npm run prettier:check

**Expected behavior**
Checks the vue, js files with prettier.

**Screenshots**
> bento-starter@0.1.0 prettier:check D:\Workspace\StatsApp\bento-starter
> prettier '**/*.{vue,js}' --list-different

[error] No matching files. Patterns tried: '**/*.{vue,js}' !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bento-starter@0.1.0 prettier:check: `prettier '**/*.{vue,js}' --list-different`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the bento-starter@0.1.0 prettier:check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by kefranabg** [comment]
Hi @RoyBkker,

Thanks for the report.

This is probably related to how windows interpret quotes in npm scripts.

In `package.json`, replacing ` "prettier:check": "prettier '**/*.{vue,js}' --list-different"` with ` "prettier:check": "prettier \"**/*.{vue,js}\" --list-different"` will propbably fix the issue.

I'll open a Pull Request 😉

**Comment by kefranabg** [comment]
Fixed in #156

Thanks for opening the issue ! 👍
