### ISSUE TITLE
Use setup to customize project with new name

### ISSUE THREAD

**Issue by GregoryBevan** [kefranabg/bento-starter#160]
**Is your feature request related to a problem? Please describe.**
The amazing __bento-starter__ name is used in specific files like _package.json_ and others. It would be great if the setup from #140 also allows to customize files not specific to git.

**Describe the solution you'd like**
Add a function to the setup command to replace technical occurrences to _bento-starter_ with a choosen project name

**Comment by tbetous** [comment]
This will be fix after that #140 will be merged !

Thanks for your issue !

**Comment by kefranabg** [comment]
It should replace 'bento starter' label in : 
- [ ] `package.json` name value
- [ ] `package-lock.json` name value
- [ ] `/public/manifest.json` name value
- [ ] Vue head complement value
- [ ] Vue head meta descriptions
- [ ] Navbar title
- [ ] `VUE_APP_TITLE` env variable in `.env.example` or `.env.local` 
- [ ] in `public/index.html`
- [ ] in`AppleAddToHomeScreenModal.vue` file

We should use env variable to handle this easily.

**Comment by MaeseppTarvo** [comment]
@kefranabg in `package.json` there is also the "_id" which has to change if you want to change the `service-worker.json` cache name prefix
