### ISSUE TITLE
CI/CD Please upgrade your Node version.

### ISSUE THREAD

**Issue by Foetus6907** [kefranabg/bento-starter#171]
**Describe the bug**
Can't finalize CI/CD setup.
Jobs failed with this error message : 
npm run lint
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.1
npm info lifecycle bento-starter@0.1.0~prelint: bento-starter@0.1.0
npm info lifecycle bento-starter@0.1.0~lint: bento-starter@0.1.0

> bento-starter@0.1.0 lint /home/circleci/repo
> vue-cli-service lint

 ERROR  You are using Node v7.10.1, but vue-cli-service requires Node >=8.
Please upgrade your Node version.

I don't understand why it's saying that i'm using Node v7.10.1. As on my laptop i have version 10 install. I have even change the version in package.json to "engines": {
    "npm": ">=6.4.0",
    "node": ">=10.5.0"
  },

**Comment by kefranabg** [comment]
Hi @Foetus6907 ,

Can you provide: 
- Your OS
- Node version
- Npm version
- Which command gives you this error

You get this error when running a command on your laptop right ?

**Comment by kefranabg** [comment]
Hi @Foetus6907,

Can you provide more information on how you are running the CI process ?

**Comment by Foetus6907** [comment]
I followed the setup instructions of your documentation. Every push on GitHub stat a CI job

**Comment by kefranabg** [comment]
Did you change the `.circleci/config.yml` file ? 

> ERROR You are using Node v7.10.1, but vue-cli-service requires Node >=8.

I can't figured out how it's possible as the circleci config uses `cypress/base:10` image that embeds `node:10.13`
In addition, all builds on master are currently passing.

Could you provide a link to your github project ?

**Comment by Foetus6907** [comment]
hi @kefranabg, sorry for that it's my mistake.
Instead of clonning your project i download the zipfile. As i'm working on mac os it's appear that .circle folder was like a hidden folder, so it didn't get copy paste. So as i didn't find it in the project, when following your documentation. So i wrote my own yaml file, based on sample provided by CircleCI which was initially config with Node 7.10.
