### ISSUE TITLE
Add email / password firebase authentication

### ISSUE THREAD

**Issue by zemiguelll** [kefranabg/bento-starter#179]
**Is your feature request related to a problem? Please describe.**
Currently Google authentication is provided as an app embedded feature, which is great! However this is not always the go-to authentication method for most apps.

**Describe the solution you'd like**
It would be great to additionally have the option to register + login using the email and password firebase method. As an extra, additional parameters could be passed (for example "displayName", "logoURL" or accountType).

**Comment by perkinsjr** [comment]
IF you could imagine this as a solution:

I had implemented a register with display Name email and password. 

Then on the login adding adding additional two fields for the user and password. Then using a switch case to handle the google auth vs email giving flex to the abilty to extend for twitter,fb etc. 

Thoughts on this implementation ? 

I think I would have time this week to implement this.

**Comment by zemiguelll** [comment]
I believe this would be a great starting point, if @kefranabg agrees!
We would have email / password firebase authentication together with Google authentication and would be ready for further authentication methods.
Furthermore we would already have an example of how to update the Display Name - maybe we could even add another example for a custom parameter.

**Comment by perkinsjr** [comment]
Quick Update I have the Registration functionality done and ready. I just have to style the inputs to look the same. I should be able to create a pull request today / tomorrow.

**Comment by kefranabg** [comment]
Thanks @perkinsjr @zemiguelll for helping on this 😉 
Do not hesitate to submit a pull request right now and tag it as “Work In Progress“. It would allow us to give a first opinion so it can go to the right direction ! 👍

**Comment by perkinsjr** [comment]
@kefranabg as soon as I get home. I will set the pull request.

**Comment by kefranabg** [comment]
Hi @perkinsjr, thank you so much for your work on this PR (and on bento in general) 🙏 We discussed a lot with @tbetous about this feature, and unfortunately, we ended up with the idea that it's developer's responsibility to add this feature if he wants to (just to keep the boilerplate as simple as possible) 😕 Sorry about that, we messed up on that one 😅 We shouldn't have open this issue before being sure that we wanted to add it ...

**Comment by perkinsjr** [comment]
Hey @kefranabg and @tbetous maybe should take the code and add an example in the documentation for extending the platform. Either way it's not wasted time both for you or I as it shows how to add custom profiles etc.

**Comment by kefranabg** [comment]
I like the idea of keeping your branch and reference it in the documentation for users that might be interested !
