### ISSUE TITLE
npm run setup errors on macOS and latest stable npm and node

### ISSUE THREAD

**Issue by MaeseppTarvo** [kefranabg/bento-starter#185]
I am on macOS and these are my npm and node versions:

```
npm --v
6.9.0
node -v
v12.3.1
```

[This](https://gist.github.com/MaeseppTarvo/2a4defc6825967d02be9c8f40cb4c4a1) is the log I get if running `npm run setup` as mentioned in documentation.

I also tried using node v10.16.0I and npm 6.9.0. Also tried using Yarn but I still run into warnings/errors. Which should be the latest version?

Can you point me to the right direction? Since the documentation requirement says node9.3.0 **+** and npm@5.5.0 **+** I thought that using newest stable versions would be fine, correct me if I am wrong.

**Comment by MaeseppTarvo** [comment]
Removing the package-lock.json file and running yarn install did the trick.

**Comment by kefranabg** [comment]
Hi @MaeseppTarvo, it seems that the install error is coming from `iltorb`dependency (which is not compatible with node 12 in iltorb `1.3`) but it's an optional dependency so it won't break the install. Just ignore the error 😉

You can either downgrade to node v11 if you don't want this error or just ignore it during deps install with node 12.

**Comment by MaeseppTarvo** [comment]
@kefranabg Okay, thank you very much for responding so quickly. I just realized that if I use yarn, the setup script won't run and if running it manually "yarn run setup" then it is going to uninstall all packages and installs them with npm. Anyway, I am gonna try to use the node v11 and hope the best.

**Comment by kefranabg** [comment]
I'll do a PR to update `iltorb` dependency so you'll be able to install bento-starter with node v12 without errors 😉

**Comment by MaeseppTarvo** [comment]
Thank you very much, can't wait to get it to work 😊.

**Comment by kefranabg** [comment]
Not sure to understand your question, but you can avoid `npm run setup` script and run `npm install`. You can change the remote git origin [whenever you want](https://help.github.com/en/articles/changing-a-remotes-url)

**Comment by MaeseppTarvo** [comment]
The only command I want to avoid is `npm install` because I am trying to use yarn. But I want to run scripts that are in package.json so it will ask if I want to start new repo, removing useless resources etc

**Comment by kefranabg** [comment]
You can use `npm run setup`, remove `node_modules` and install dependencies again with `yarn` then
