### ISSUE TITLE
Not working on chrome ios

### ISSUE THREAD

**Issue by kefranabg** [kefranabg/bento-starter#188]

**Comment by perkinsjr** [comment]
This also happens on iOS Safari See GIF for reference

![Bento-iOS](https://user-images.githubusercontent.com/45409975/59348909-5bade300-8ce6-11e9-8ec9-8ed4c33f64a6.gif)

**Comment by kefranabg** [comment]
Thanks for the report 😉 
Can you provide your IOS version ?

**Comment by perkinsjr** [comment]
That version was iOS 11 on iPhone X I tested on an XS on iOS 12 and Safari works great. Both Using BrowserStack to do testing. 

I also tested on a Samsung S9, with Chrome, Firefox, Samsung Browser, everything is functioning great. 

I assume whatever broke the Chrome version, broke that version..

**Comment by kefranabg** [comment]
Fixed in in [this commit](https://github.com/kefranabg/bento-starter/commit/db74a23d4003e26b3f153be23a5fe6aedd6473ec)
