### ISSUE TITLE
Missing permissions on firebase

### ISSUE THREAD

**Issue by phiter** [kefranabg/bento-starter#194]
Hi!

I'm starting a new project and I followed all the steps on the setup guide, and on the CI step, on the very last part, I'm getting a permissions error on the last step of the CI build step.

This is the error I'm getting:

```
#!/bin/bash -eo pipefail
if [[ "$CIRCLE_BRANCH" == "master" ]]; then
  npm run firebase:deploy:ci
fi

> bento-starter@1.0.0 firebase:deploy:ci /root/project
> firebase deploy --non-interactive --token $FIREBASE_TOKEN


Error: Authorization failed. This account is missing the following required permissions on project bento-starter:

  datastore.indexes.create
  datastore.indexes.delete
  datastore.indexes.list
  datastore.indexes.update
  firebase.projects.get
  firebasehosting.sites.update
```

Is the documentation missing something or did I mess up somewhere?

**Comment by phiter** [comment]
Ok, so this commit fixed it: 
https://github.com/phiter/devskiller/commit/7bda99dc4531bb70f805aabcef6e22481c13249b

I didn't update my repo after setting up .firebaserc
Maybe add that to the documentation, just in case someone is as dumb as me!

**Comment by kefranabg** [comment]
Hi @phiter 

If you're talking about this step :

```
# Select the project you've just created and use "default" as alias
npx firebase use --add 
```

It' already in the documentation 😅 

👉  [https://bento-starter.netlify.com/setup/#step-2-firebase-configuration](https://bento-starter.netlify.com/setup/#step-2-firebase-configuration)

**Comment by phiter** [comment]
I ran this step but it didn't change the "default" project to my own. It was still bento-starter.

I removed my repo, I'll learn Firebase later. I loved the project tho, great job you guys!
