### ISSUE TITLE
Add a contributor page

### ISSUE THREAD

**Issue by tbetous** [kefranabg/bento-starter#199]
Add a contributor page based on https://api.github.com/repos/kefranabg/bento-starter/contributors

**Comment by geromegrignon** [comment]
i'll work on it this week.

**Comment by tbetous** [comment]
Hi @geromegrignon ,

I started to work on this issue yesterday. If you want I can share my code in a branch but there is no problem if want to code it from scratch. It is always a pleasure to see that someone want to contribute to bento-starter.

Here is just a check list of things to do but feel free to do as you want if you think there is a better way :

- [ ] Create a new contributor state (state/mutation/action)
- [ ] Create a new view Contributors
- [ ] Create a component ContributorList that take as prop a list of contributors
- [ ] Create a component ContributorItem that take as prop a contributor
  - [ ] The contributor item shoud display avatar in round picture
  - [ ] The contributor item shoud display pseudo
  - [ ] The contributor item should be clickable and redirect the user to the contributor github page.
- [ ] The lighthouse test should not be lowest than the actual.

Is it OK for you ?

**Comment by geromegrignon** [comment]
I just watched your commit.
I wonder how you plan to integrate it into the project : inside the master or a separate branch just to display the contributor page on the current version on Netlify, as it'll add unnecessary content people will have to delete on first use (so not fitting the 'starter' usage).

**Comment by tbetous** [comment]
@geromegrignon ,

I tought about what you said and you're totally right ! There is no point to make this in bento-starter but it makes more sens to add this in [bento-starter-docs](https://npm.pkg.github.com/kefranabg/bento-starter-docs).

That makes this task a little more complexe because you need to add bento-starter and bento-starter-docs contributors. 

I will let my branch because it can be useful for develop this in bento-starter-docs. 

Do you want to be assigned to this issue ?

**Comment by geromegrignon** [comment]
Sure but we should may be close this current issue to open one into the documentation repo (as it'll be easier to track commits related to the issue).

**Comment by tbetous** [comment]
Done ;)

This issue moved here => https://github.com/kefranabg/bento-starter-docs/issues/12
