### ISSUE TITLE
Generic DB - readAll constraints, please provide example.

### ISSUE THREAD

**Issue by rlightner** [kefranabg/bento-starter#203]
Don't understand how this is supposed to be use, should it be an array of an array? 

How would compound queries be implemented?

**Comment by kefranabg** [comment]
Hi @rlightner,

There already is an example in the doumentation, in the  [cloud database section](https://bento-starter.netlify.com/guide/#cloud-database).

The Generic db source code is also available in the project, feel free to read it if you want more details. 😉

**Comment by rlightner** [comment]
Totally right, sorry about this, I'm so used to just looking at the repo with no docs available!

**Comment by gjdipietro** [comment]
@rlightner 

Do you have an example or a recommended way to use limit, orderBy, or startAt with the readAll method?  It seems like readAll is only configured to work with conditions that work on the .where()

**Comment by kefranabg** [comment]
@gjdipietro you can extend GenericDB with your custom functions to do this job
