### ISSUE TITLE
Desktop install app support

### ISSUE THREAD

**Issue by guastallaigor** [kefranabg/bento-starter#207]
**Is your feature request related to a problem? Please describe.**
Hello. great project!
Not sure if would be possible or worth it to develop something like this, but I was just wondering if would be possible to download/install the application like a desktop app. I've browsed the source code for a bit but didn't find anything regarding this feature.

**Describe the solution you'd like**
I didn't try it myself, but maybe by adding some listeners like `beforeinstallprompt` and `appinstalled`, this could be possible.

**Describe alternatives you've considered**
Adding this by myself in a project after starting it with bento starter, and don't add this to the main source code.

**Additional context**
Could be also a developer configuration saying that he wants or not the option to install as a desktop application.

**Comment by guastallaigor** [comment]
Closing this because I think it's a duplicate of #165.

**Comment by kefranabg** [comment]
Hi @guastallaigor ,

This will be available in chrome 76 (coming soon 😉) Already available in chrome canary : [see my tweet](https://twitter.com/FranckAbgrall/status/1127897581437300738).

You can also create [your own install desktop button](https://developers.google.com/web/progressive-web-apps/desktop).

Hope this helped you 😉
