### ISSUE TITLE
Need to fix vulnerabilities

### ISSUE THREAD

**Issue by tbetous** [kefranabg/bento-starter#208]
Need to fix this when `npm install`
```
added 7 packages from 7 contributors, removed 5 packages, updated 9 packages and audited 54821 packages in 8.928s
found 1072 vulnerabilities (64 low, 1 moderate, 1007 high)
```

**Comment by yannbertrand** [comment]
Hey, can I use this issue to show how to do a PR? Thank you ❤️

**Comment by yannbertrand** [comment]
FYI some audit errors require an @vue/cli-plugin-unit-jest update by itself (it has to require jest@24 so probably on v4 release). See https://github.com/vuejs/vue-cli/issues/3450
