### ISSUE TITLE
npm ERR! code ELIFECYCLE when running 'npm run build' command 

### ISSUE THREAD

**Issue by wizlearner** [kefranabg/bento-starter#212]
Building for production...Webpack Bundle Analyzer saved stats file to /Users/khushbookhullar/bwizly/dist/stats.json
ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bento-starter@1.0.0 build: vue-cli-service build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bento-starter@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/khushbookhullar/.npm/_logs/2019-08-22T10_59_14_802Z-debug.log
Khushboos-MacBook-Air:bwizly khushbookhullar$

**Comment by kefranabg** [comment]
Hi @wizlearner,

We need more context to help you.
Please respect the issue bug report template.
