### ISSUE TITLE
How to add Firebase config variables?

### ISSUE THREAD

**Issue by johnatasjmo** [kefranabg/bento-starter#223]
**Is your feature request related to a problem? Please describe.**
init.js file has been commited with firebase app variables

**Describe the solution you'd like**
To configure variables within firebase, circleci

**Describe alternatives you've considered**
Researching

**Additional context**
Github shows a warning that app credentials have been exposed

**Comment by kefranabg** [comment]
Hi @johnatasjmo,

Firebase variables are not sensitive data, so you can safely publish them in your code (even if Github recognize them as secret credentials)
