### ISSUE TITLE
The slack link in README.md is broken

### ISSUE THREAD

**Issue by Plantain** [kefranabg/bento-starter#225]
Clicking it (https://bento-starter.slack.com/join/shared_invite/enQtNjE5OTI5MzQyMTE3LTVjYjM3YjMzMGQ4NjgzYzY5YWMwNDkyY2VmMzg4ODg0OTkwZDRhMzg3OWU0MGY1MGYwMmVjYThiMmU2YzBjODY)  yields "This invite link is no longer active."

**Comment by kefranabg** [comment]
Fixed! Thanks for the report
