### ISSUE TITLE
updated ESLint-plugin-import peer dependency breaking

### ISSUE THREAD

**Issue by hwlmatt** [kefranabg/bento-starter#227]
**Describe the bug**
The recent release of 2.19.0 and 2.19.1 of eslint-plugin-import introduce some errors. Specifically installing 2.18.2 (and not running install as ^2.18.2) resolves this for now at least.

**To Reproduce**
When adding the following peer dependency:
`eslint-config-airbnb@18.0.1 requires a peer of eslint-plugin-import@^2.18.2`

`npm i eslint-plugin-import@^2.18.2` will install 2.19.1 and  result in the following errors (27 times for some version of):

```
error: Missing file extension for "@/router"

import router from ‘@/router’

```
Downgrading to 2.19.0  results in the following error:
 ```
ERROR  TypeError: Cannot read property 'value' of null
Occurred while linting /Users/md/www/bento-debug/src/misc/helpers.js:7
```

And 2.18.2 (the version before 2.19.0) seems to be the latest that runs without error, so be sure to install the dependency specific to that version unless this is resolved using:

`npm i eslint-plugin-import@2.18.2`

**Additional context**
This is more a heads up for anyone recklessly installing peer dependencies (as I was) and then inheriting this mess of new errors. 
From what I have read, however, there may be some configuration options to help thwart this; perhaps along the lines of `eslint-import-resolver-webpack`
[eslint-import-resolver-webpack on npm site](https://www.npmjs.com/package/eslint-import-resolver-webpack)
But I really don't know. Putting that link above as a resource for those that would know, not as a suggested solution.

**Comment by kefranabg** [comment]
Hey, is this because you've updated `eslint-plugin-import` ?

**Comment by hwlmatt** [comment]
Hey, yeah in installing/updating dependencies to the latest accepted by the package.json (`"eslint-plugin-import": "^2.17.3"`) it will of course with the `^` take that to 2.19.1 (coincidently also the latest release for eslint-plugin-import).
 
But 2.18.2 is the latest I can use with out creating the errors mentioned above.

On my fork, I removed the `^` and locked it to 2.18.2 version to avoid updating beyond it, but may need to look into the specific cause of the above errors.

**Comment by kefranabg** [comment]
What dependency did you updated to get this error? `eslint-config-airbnb` ? `eslint-config-airbnb-base` ? Have you tried to update both to fix the problem?

My opinion is that this problem is not related to bento-starter, you should probably report this to the corresponding repos and try to get some help there. (Maybe `eslint-config-airbnb` or `eslint-plugin-import` ?)

**Comment by hwlmatt** [comment]
`eslint-config-airbnb` still on 18.0.1 and `eslint-config-airbnb-base` still on 14.0.0

My initial post is more of a _heads up_ since the peer dependency notification will request `eslint-plugin-import@^2.18.2` and that will give you 2.19.1 

JUST updating `eslint-plugin-import` will reproduce, so I imagine it's a change on their end; just wasn't sure what that change is yet, and whether that change created an issue to be addressed with `eslint-plugin-import`, `eslint-config-airbnb`, or  within bento-starter.

Cheers and thanks
-------------
(for what it is worth, I was able to update the vast majority of dependencies to latest versions without much more than a few lint changed files along the way. The david-dm of my fork: [https://david-dm.org/hwlmatt/bento-starter](https://david-dm.org/hwlmatt/bento-starter)

**Comment by kefranabg** [comment]
Can I close the issue then?
