### ISSUE TITLE
Install Vuetify

### ISSUE THREAD

**Issue by johnatasjmo** [kefranabg/bento-starter#228]
**Is your feature request related to a problem? Please describe.**
Not able to install Vuetify with Vue CLI

**Describe the solution you'd like**
```vue add vuetify```

**Describe alternatives you've considered**
```npm install @nuxtjs/vuetify -D```

**Additional context**
Error when running ` vue add vuetify `
```
Installing vue-cli-plugin-vuetify...
npm ERR! path /Users/johnatas/projects/humus/node_modules/grpc/node_modules/abbrev
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/johnatas/projects/humus/node_modules/grpc/node_modules/abbrev' -> '/Users/johnatas/projects/humus/node_modules/grpc/node_modules/.abbrev.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
```

Please let me know if there is other alternative.

**Comment by tbetous** [comment]
Hi @johnatasjmo,

Thanks for reporting this issue !

I tested all the installation and I did not have any problem. Did you first run `npm setup` before installing vuetify ? 

Is you vue CLI up to date ?

**Comment by kefranabg** [comment]
I close the issue as the problem seems to be solved
