### ISSUE TITLE
Type inconsistency when creating new products or loading products from Database

### ISSUE THREAD

**Issue by sceee** [kefranabg/bento-starter#229]
**Describe the bug**
The `Timestamp` to Date` conversion for objects behaves differently for newly created products and existing products that are converted via `convertObjectTimestampPropertiesToDate` in `generic-db.js`.

The crucial parts in `generic-db.js` are:
`create` method sets `createTimestamp` and `updateTimestamp` directly to a `Date`:
```
...
return {
      id: docId,
      ...data,
      createTimestamp: new Date(), <<<<<< Type is Date
      updateTimestamp: new Date() <<<<<< Type is Date
    }
```
...whereas `read` and `readAll` methods use `convertObjectTimestampPropertiesToDate` to convert the timestamps from Firestore to `Date`s.
But the issue is that in `convertObjectTimestampPropertiesToDate`, existing properties are not replaced but a new `newObj` object is added with the converted values.
```
return {
      ...obj,
      newObj
    }
```

So in the end, a loaded product from the database looks like this:
```
product: {
  ...,
  createTimestamp <<< Timestamp
  updateTimestamp <<< Timestamp
  newObj: {
    createTimestamp <<< Date
    updateTimestamp <<< Date
  }
}
```

**To Reproduce**
1. Load Products page
2. Set breakpoint in the browser to investigate objects

**Expected behavior**
Objects have the same properties with the same types when being loaded from the DB or returned from the `create` method.

**Comment by sceee** [comment]
Actually I guess this could be the fix:
```
  convertObjectTimestampPropertiesToDate(obj) {
    keys(obj)
      .filter(prop => obj[prop] instanceof Object)
      .forEach(prop => {
        if (obj[prop] instanceof firebase.firestore.Timestamp) {
          obj[prop] = obj[prop].toDate()
        } else {
          this.convertObjectTimestampPropertiesToDate(obj[prop])
        }
      })

    return {
      ...obj
    }
  }
```

What do you think?

**Comment by kefranabg** [comment]
hi @sceee, thanks for the report.

You're right this is a bug. Actually the fix is `
return {
...obj,
...newObj
}
`

I'm fixing it right now

**Comment by kefranabg** [comment]
Fixed in https://github.com/kefranabg/bento-starter/commit/e3adb75b84bac32d8d663d9c5b300641a46e1e61

**Comment by sceee** [comment]
Thanks @kefranabg ! 👍
