### ISSUE TITLE
Use Typescript for application code for improved developer experience

### ISSUE THREAD

**Issue by sceee** [kefranabg/bento-starter#230]
**Is your feature request related to a problem? Please describe.**
Writing application code in standard javascript is hard and error-prone since there are no type checks and intellisense/code completion also works just rudimentary in VSCode.

**Describe the solution you'd like**
The application code is written in Typescript, so fully typed and all other features work as expected when running `npm run serve`. So it is possible to debug the typescript code via sourcemaps.

**Describe alternatives you've considered**
I did not consider alternatives but Flow could also be an alternative as static type checker.

**Additional context**
n/a

**Comment by kefranabg** [comment]
Hey @sceee thanks for opening this issue.

I don't want to constraint all users to use typescript. If they want to use it, they can easily add it to the current stack.

**Comment by paolodina** [comment]
It would be nice to document how. I'm just learning Typescript (and interested in using it for next projects), so maybe I could write something and submit to your attention. @kefranabg @sceee
