### ISSUE TITLE
How to integrate vuexfire?

### ISSUE THREAD

**Issue by eparizzi** [kefranabg/bento-starter#234]
I'm trying to integrate [vuexfire ](https://vuefire.vuejs.org/vuexfire/)into this project but I don't have a lot of experience in Vue at all.

Would you consider adding this integration?  If not, maybe a little guidance on how to add it would be greatly appreciated.

Thank you!

**Comment by kefranabg** [comment]
Hi,

Setting up vuexfire in bento-starter is exactly de same as setting up vuexfire in a simple vue.js application.

It already exists a lot of documentation/example to do so. This is why I won't  add any resources to explain it as it would just duplicate existing content.

Thanks for asking though!
