### ISSUE TITLE
Differences with Nuxt.js

### ISSUE THREAD

**Issue by Kimeiga** [kefranabg/bento-starter#236]
Thank you so much for publishing this starter. It looks to me like literally the best way to go from 0 to PWA full stack web app in as little time as possible with the best framework possible (vue, all things considered).

How would you say that this project is different structurally from Nuxt.js? Disregarding how bento has firebase support out of the box

**Comment by kefranabg** [comment]
Hi @Kimeiga 

Bento allows you to quickly get a full stack environment with a lot of tools. It is very opinionated stack.

Nuxt goal is not the same as bento starter. Nuxt is better if you want a SSR website or a static generated website, but it does not provide quality tools, CI, database as bento does.

**Comment by Kimeiga** [comment]
Cool cool thank you I'll try bento!
