### ISSUE TITLE
Unable to complete setup.

### ISSUE THREAD

**Issue by CiaranPearse** [kefranabg/bento-starter#240]
**Describe the bug**
Consistently getting following error in console on multiple setup attempts.
`Uncaught (in promise) TypeError: firebase_app__WEBPACK_IMPORTED_MODULE_1___default.a.firestore is not a function`

**To Reproduce**
1. Follow instructions exactly.
2. Click on login (creates record in DB but hangs on "Authenticating..." screen. Error visible in console.)
3. Click on products (Shows loading screen but hangs. Error visible in console.)

**Screenshots**
<img width="1411" alt="Screen Shot 2020-03-08 at 4 54 45 PM" src="https://user-images.githubusercontent.com/630810/76167345-cf89f880-615d-11ea-9b2b-1fdab426e093.png">
<img width="1396" alt="Screen Shot 2020-03-08 at 4 55 04 PM" src="https://user-images.githubusercontent.com/630810/76167349-d44eac80-615d-11ea-8bea-22cc4a695dc6.png">
<img width="754" alt="Screen Shot 2020-03-08 at 5 00 20 PM" src="https://user-images.githubusercontent.com/630810/76167419-622a9780-615e-11ea-9db0-65bf0c93b438.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3
 - Browser: Chrome
 - Version: 80.0.3

**Comment by kefranabg** [comment]
Hey, what node version are you using?
