### ISSUE TITLE
Create a CLI

### ISSUE THREAD

**Issue by kefranabg** [kefranabg/bento-starter#53]

**Comment by tbetous** [comment]
I think we could do a first version with just init command. Several questions would be asked =>

What is you project name ?
What is your firebase confirguration ?

If we make a cli, I think the #18 will be necessary !

**Comment by kefranabg** [comment]
Why would we need versioning to build the cli ?

**Comment by tbetous** [comment]
In order to publish it into npm.

**Comment by Sharlaan** [comment]
Nice boilerplate !

Suggestions for CLI-building :
- [Enquirer](https://github.com/enquirer/enquirer) : very nice looking prompts
- [GlueGun](https://github.com/infinitered/gluegun) : all-in-one toolbox (including Enquirer)
