### ISSUE TITLE
Login should not be possible offline

### ISSUE THREAD

**Issue by tbetous** [kefranabg/bento-starter#80]
When I am offline and not logged in. When I click on product, the view is redirected to login and I have the posibility to log with google. 

This should not possible.

**Comment by tbetous** [comment]
I will probably alter the content of login page in order to display a message "Please check your connetion, login feature is not available offline". What do you think about that @kefranabg  ?

**Comment by kefranabg** [comment]
Hey ! I fixed this issue in #69, even if the user click the login button while being offline, it will display an error message from `firebase-auth`

**Comment by tbetous** [comment]
Yes I saw this and that's great ! But I think the login page should not display option in case of offline. 

![example](https://user-images.githubusercontent.com/4435536/55274982-2c8af680-52df-11e9-8109-571bcce5dae1.gif)

It would be more UX firendly to have a screen like that than an error :

![image](https://user-images.githubusercontent.com/4435536/55274980-25fc7f00-52df-11e9-8a85-b54615902fff.png)

**Comment by kefranabg** [comment]
You're right 😄
